# Generated by Django 5.0.3 on 2024-03-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_date_joined_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='publicado_por',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='publicacao',
            old_name='publicado_por',
            new_name='autor',
        ),
    ]
